### PR TITLE
MAKE CMDUCONF NO U AGAIN!

### PR DESCRIPTION
**Pull request by neonichu**
cc @b3ll

### CODE REVIEW

**Comment by Abizern** [comment]
👍 
😈

**Comment by b3ll** [comment]
19/10 please merge 

hopefully you'll actually merge, unlike @KrauseFx

**Comment by neonichu** [comment]
dat @KrauseFx, always rejecting the great PRs

**Comment by neonichu** [comment]
BTW, you'll love to hear that while making the PR, I trolled myself by also changing the git remotes :joy: 

```
$ git remote -v
origin  git@github.com:neonichu/cmdnouconf.github.io.git (fetch)
origin  git@github.com:neonichu/cmdnouconf.github.io.git (push)
upstream    git@github.com:cmdnouconf/cmdnouconf.github.io.git (fetch)
upstream    git@github.com:cmdnouconf/cmdnouconf.github.io.git (push)
```

**Comment by b3ll** [comment]
😂😂😂😂

**Comment by wolffan** [comment]
WAIT, this is how open source works 😮 

I'd say let's leave cmdnouconf for next year :trollface:

**Comment by KrauseFx** [comment]
@b3ll we still have merge conflicts that need to be resolved 😢

**Comment by neonichu** [comment]
@KrauseFx no u are a merge conflict 😂

**Comment by neonichu** [comment]
8h and this has still not been merged :rage1: :rage2: :rage3: :rage4:

**Comment by wolffan** [comment]
@neonichu I have philosophical conflicts

**Pull request closed without merging**
